template = ""
rev_id = 4
template_sha = "87be02986858c4b7ae5e8613b6f951c3c209b221"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "kl"
__UND2C_TRG__ = "en"
__UNDEFINED_SOURCE__ = "Greenlandic"
__UNDEFINED_TARGET__ = "English"
__UND_SRC__ = "kal"
__UND_TRG__ = "eng"
